"""Generate keywords.jsonl: one keyword per line, same schema as data.jsonl.

Each record is {"emoji": <emoji>, "feeling": "Neutral", "text": <keyword>}.
The keyword list is a hand-curated set of words/short phrases associated with
each emoji in labels.json. Run with: uv run gen_keywords.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent
LABELS = json.loads((ROOT / "labels.json").read_text())

# emoji -> list of associated keywords (single words or short phrases)
KEYWORDS: dict[str, list[str]] = {
    "😀": [
        "smile",
        "grin",
        "grinning",
        "happy",
        "cheerful",
        "beaming",
        "joy",
        "smiley",
        "delighted",
        "pleased",
        "glad",
        "friendly",
        "big smile",
    ],
    "😂": [
        "laughing",
        "lol",
        "lmao",
        "rofl",
        "hilarious",
        "funny",
        "laugh",
        "crying laughing",
        "humor",
        "joke",
        "giggles",
        "chuckle",
        "hysterical",
    ],
    "🥹": [
        "touched",
        "emotional",
        "grateful",
        "moved",
        "teary",
        "bittersweet",
        "heartwarming",
        "proud",
        "overwhelmed",
        "sentimental",
        "holding back tears",
    ],
    "😍": [
        "love",
        "adore",
        "crush",
        "infatuated",
        "heart eyes",
        "smitten",
        "admiration",
        "gorgeous",
        "beautiful",
        "obsessed",
        "love struck",
    ],
    "🤔": [
        "thinking",
        "pondering",
        "hmm",
        "wondering",
        "considering",
        "curious",
        "contemplating",
        "doubt",
        "question",
        "reflecting",
        "puzzled",
    ],
    "🥳": [
        "celebration",
        "party",
        "birthday",
        "congrats",
        "festive",
        "hooray",
        "celebrate",
        "party horn",
        "confetti",
        "woohoo",
    ],
    "😎": [
        "cool",
        "sunglasses",
        "confident",
        "chill",
        "swag",
        "awesome",
        "slick",
        "boss",
        "unbothered",
        "deal with it",
    ],
    "😭": [
        "crying",
        "sobbing",
        "tears",
        "bawling",
        "heartbroken",
        "weeping",
        "devastated",
        "wailing",
        "ugly cry",
        "so sad",
    ],
    "💀": [
        "skull",
        "dead",
        "death",
        "dying",
        "skeleton",
        "bones",
        "spooky",
        "morbid",
        "danger",
        "poison",
        "im dead",
    ],
    "🔥": [
        "fire",
        "flame",
        "lit",
        "hot",
        "burning",
        "blaze",
        "heat",
        "wildfire",
        "campfire",
        "straight fire",
    ],
    "❤️": [
        "love",
        "heart",
        "romance",
        "affection",
        "valentine",
        "devotion",
        "adore",
        "care",
        "sweetheart",
        "red heart",
    ],
    "💯": [
        "hundred",
        "perfect",
        "hundred percent",
        "agreed",
        "full marks",
        "score",
        "absolutely",
        "spot on",
        "keep it real",
    ],
    "✨": [
        "sparkle",
        "shine",
        "glitter",
        "magic",
        "shimmer",
        "glimmer",
        "dazzle",
        "stars",
        "clean",
        "brand new",
        "special",
    ],
    "👍": [
        "thumbs up",
        "approve",
        "okay",
        "yes",
        "agree",
        "like",
        "good",
        "nice",
        "sounds good",
        "will do",
    ],
    "👏": [
        "clap",
        "applause",
        "bravo",
        "well done",
        "cheer",
        "ovation",
        "congrats",
        "praise",
        "kudos",
    ],
    "🙌": [
        "praise",
        "hooray",
        "celebration",
        "raised hands",
        "hallelujah",
        "yay",
        "triumph",
        "relief",
        "thank goodness",
    ],
    "🙏": [
        "prayer",
        "pray",
        "please",
        "thank you",
        "gratitude",
        "hope",
        "blessing",
        "namaste",
        "plea",
        "grateful",
    ],
    "💪": [
        "strong",
        "muscle",
        "strength",
        "flex",
        "power",
        "gym",
        "workout",
        "biceps",
        "tough",
        "fitness",
        "gains",
    ],
    "🧠": [
        "brain",
        "mind",
        "smart",
        "intelligence",
        "think",
        "knowledge",
        "brainy",
        "neurons",
        "memory",
        "genius",
    ],
    "👀": [
        "eyes",
        "looking",
        "watching",
        "see",
        "peek",
        "suspicious",
        "spying",
        "attention",
        "staring",
        "look",
    ],
    "🐶": [
        "dog",
        "puppy",
        "doggo",
        "pup",
        "canine",
        "pooch",
        "hound",
        "woof",
        "pet",
        "good boy",
    ],
    "🐱": [
        "cat",
        "kitten",
        "kitty",
        "feline",
        "meow",
        "tabby",
        "whiskers",
        "pet",
        "house cat",
    ],
    "🦁": [
        "lion",
        "king",
        "mane",
        "jungle",
        "safari",
        "leo",
        "roar",
        "big cat",
        "pride",
        "wild",
    ],
    "🦉": [
        "owl",
        "night owl",
        "wise",
        "hoot",
        "bird",
        "nocturnal",
        "wisdom",
        "feathers",
    ],
    "🐙": [
        "octopus",
        "tentacles",
        "sea creature",
        "cephalopod",
        "ocean",
        "eight arms",
        "kraken",
        "marine",
    ],
    "🌲": [
        "tree",
        "pine",
        "forest",
        "evergreen",
        "woods",
        "nature",
        "conifer",
        "spruce",
        "wilderness",
        "hiking",
    ],
    "🌺": [
        "flower",
        "hibiscus",
        "bloom",
        "tropical",
        "blossom",
        "floral",
        "petal",
        "hawaii",
        "garden",
    ],
    "🌈": [
        "rainbow",
        "colors",
        "pride",
        "spectrum",
        "arc",
        "hope",
        "colorful",
        "prism",
        "after the rain",
    ],
    "☀️": [
        "sun",
        "sunny",
        "sunshine",
        "daylight",
        "bright",
        "summer",
        "solar",
        "warmth",
        "clear sky",
    ],
    "⭐": [
        "star",
        "favorite",
        "rating",
        "shine",
        "gold star",
        "celebrity",
        "twinkle",
        "wish",
        "five stars",
    ],
    "🍕": [
        "pizza",
        "slice",
        "pepperoni",
        "cheese",
        "italian",
        "pie",
        "pizzeria",
        "takeout",
        "dough",
    ],
    "🌮": [
        "taco",
        "mexican",
        "tex mex",
        "tortilla",
        "taco tuesday",
        "salsa",
        "food truck",
        "filling",
    ],
    "🍣": [
        "sushi",
        "sashimi",
        "nigiri",
        "japanese",
        "raw fish",
        "rice",
        "roll",
        "wasabi",
        "seafood",
    ],
    "☕": [
        "coffee",
        "tea",
        "espresso",
        "latte",
        "cafe",
        "caffeine",
        "mug",
        "brew",
        "morning",
        "cappuccino",
    ],
    "🍺": [
        "beer",
        "brew",
        "pint",
        "ale",
        "lager",
        "pub",
        "cheers",
        "draft",
        "brewery",
        "drinks",
    ],
    "⚽": [
        "soccer",
        "football",
        "ball",
        "goal",
        "pitch",
        "world cup",
        "kick",
        "match",
        "fifa",
        "sport",
    ],
    "🎉": [
        "party",
        "celebration",
        "confetti",
        "congrats",
        "popper",
        "hooray",
        "festive",
        "new year",
        "celebrate",
    ],
    "🚀": [
        "rocket",
        "space",
        "launch",
        "spaceship",
        "blast off",
        "nasa",
        "astronaut",
        "moon",
        "orbit",
        "startup",
    ],
    "✈️": [
        "airplane",
        "plane",
        "flight",
        "travel",
        "jet",
        "airport",
        "flying",
        "vacation",
        "aviation",
        "trip",
    ],
    "🎸": [
        "guitar",
        "music",
        "rock",
        "band",
        "strings",
        "electric guitar",
        "riff",
        "strum",
        "musician",
    ],
    "💡": [
        "idea",
        "light bulb",
        "insight",
        "inspiration",
        "bright idea",
        "invention",
        "eureka",
        "lamp",
        "innovation",
    ],
    "💎": [
        "diamond",
        "gem",
        "jewel",
        "gemstone",
        "precious",
        "crystal",
        "treasure",
        "luxury",
        "bling",
    ],
    "📱": [
        "phone",
        "smartphone",
        "mobile",
        "cellphone",
        "texting",
        "screen",
        "apps",
        "call",
        "device",
    ],
    "🎁": [
        "gift",
        "present",
        "wrapped",
        "birthday",
        "surprise",
        "package",
        "bow",
        "giveaway",
        "holiday",
    ],
    "🔒": [
        "lock",
        "locked",
        "secure",
        "security",
        "privacy",
        "password",
        "padlock",
        "safe",
        "encrypted",
        "protected",
    ],
    "🌍": [
        "earth",
        "world",
        "globe",
        "planet",
        "global",
        "international",
        "environment",
        "map",
        "continents",
    ],
    "🏆": [
        "trophy",
        "award",
        "winner",
        "champion",
        "first place",
        "prize",
        "victory",
        "championship",
        "cup",
    ],
    "🎨": [
        "art",
        "painting",
        "palette",
        "paint",
        "artist",
        "creative",
        "colors",
        "canvas",
        "drawing",
        "design",
    ],
    "🔮": [
        "crystal ball",
        "fortune",
        "future",
        "prediction",
        "mystic",
        "psychic",
        "magic",
        "divination",
        "tarot",
    ],
    "📍": [
        "pin",
        "location",
        "map",
        "marker",
        "place",
        "gps",
        "destination",
        "address",
        "you are here",
    ],
    "💼": [
        "briefcase",
        "work",
        "business",
        "office",
        "job",
        "career",
        "corporate",
        "professional",
        "meeting",
    ],
    "🩺": [
        "stethoscope",
        "doctor",
        "medical",
        "health",
        "checkup",
        "nurse",
        "clinic",
        "physician",
        "healthcare",
    ],
    "💻": [
        "laptop",
        "computer",
        "coding",
        "programming",
        "tech",
        "notebook",
        "screen",
        "remote work",
        "software",
    ],
    "⏰": [
        "alarm",
        "clock",
        "time",
        "wake up",
        "morning",
        "deadline",
        "reminder",
        "alarm clock",
        "snooze",
    ],
    "🚗": [
        "car",
        "automobile",
        "drive",
        "vehicle",
        "road trip",
        "traffic",
        "sedan",
        "commute",
        "driving",
    ],
    "🌾": [
        "wheat",
        "grain",
        "harvest",
        "farm",
        "field",
        "agriculture",
        "crop",
        "rural",
        "countryside",
    ],
    "⛈️": [
        "storm",
        "thunderstorm",
        "lightning",
        "rain",
        "thunder",
        "weather",
        "downpour",
        "tempest",
    ],
    "🧩": [
        "puzzle",
        "jigsaw",
        "piece",
        "solution",
        "problem solving",
        "fit",
        "missing piece",
        "brain teaser",
    ],
    "👑": [
        "crown",
        "king",
        "queen",
        "royalty",
        "royal",
        "monarch",
        "ruler",
        "throne",
        "tiara",
        "majesty",
    ],
    "🕊️": [
        "dove",
        "peace",
        "bird",
        "pigeon",
        "freedom",
        "hope",
        "olive branch",
        "harmony",
        "tranquility",
    ],
    "🤩": [
        "star struck",
        "amazed",
        "excited",
        "wow",
        "starry eyes",
        "awesome",
        "thrilled",
        "fascinated",
        "dazzled",
    ],
    "😴": [
        "sleep",
        "sleeping",
        "tired",
        "nap",
        "zzz",
        "snooze",
        "drowsy",
        "bedtime",
        "asleep",
        "exhausted",
    ],
    "🤡": [
        "clown",
        "circus",
        "joker",
        "jester",
        "silly",
        "foolish",
        "prank",
        "makeup",
        "honk",
    ],
    "🤖": [
        "robot",
        "bot",
        "ai",
        "android",
        "machine",
        "automation",
        "cyborg",
        "mechanical",
        "artificial intelligence",
    ],
    "👻": [
        "ghost",
        "spooky",
        "halloween",
        "boo",
        "haunted",
        "spirit",
        "phantom",
        "apparition",
        "scary",
    ],
    "🤝": [
        "handshake",
        "deal",
        "agreement",
        "partnership",
        "meeting",
        "greeting",
        "cooperation",
        "contract",
        "shake hands",
    ],
    "🫡": [
        "salute",
        "respect",
        "yes sir",
        "acknowledge",
        "military",
        "honor",
        "at attention",
        "will do",
    ],
    "🫶": [
        "heart hands",
        "love",
        "appreciation",
        "thank you",
        "care",
        "gratitude",
        "adore",
        "support",
    ],
    "💔": [
        "broken heart",
        "heartbreak",
        "breakup",
        "hurt",
        "grief",
        "lost love",
        "heartbroken",
        "pain",
    ],
    "🌶️": [
        "chili",
        "pepper",
        "spicy",
        "hot",
        "jalapeno",
        "chilli",
        "heat",
        "cayenne",
        "hot sauce",
    ],
    "🍦": [
        "ice cream",
        "soft serve",
        "cone",
        "dessert",
        "sweet",
        "vanilla",
        "summer treat",
        "frozen",
    ],
    "🍩": [
        "donut",
        "doughnut",
        "pastry",
        "sweet",
        "glazed",
        "sprinkles",
        "bakery",
        "treat",
    ],
    "🎬": [
        "movie",
        "film",
        "cinema",
        "action",
        "clapperboard",
        "director",
        "hollywood",
        "filming",
        "scene",
    ],
    "🎧": [
        "headphones",
        "music",
        "audio",
        "listening",
        "podcast",
        "headset",
        "sound",
        "earphones",
        "dj",
    ],
    "🎮": [
        "gaming",
        "video game",
        "controller",
        "gamepad",
        "console",
        "play",
        "gamer",
        "esports",
        "joystick",
    ],
    "📚": [
        "books",
        "reading",
        "library",
        "study",
        "education",
        "literature",
        "textbooks",
        "learning",
        "novels",
    ],
    "🕯️": [
        "candle",
        "flame",
        "wax",
        "candlelight",
        "vigil",
        "meditation",
        "cozy",
        "light",
        "wick",
    ],
    "⚡": [
        "lightning",
        "electricity",
        "power",
        "energy",
        "bolt",
        "voltage",
        "spark",
        "charge",
        "fast",
    ],
    "🍀": [
        "clover",
        "luck",
        "lucky",
        "four leaf clover",
        "shamrock",
        "fortune",
        "st patricks",
        "irish",
        "good luck",
    ],
    "🌊": [
        "wave",
        "ocean",
        "sea",
        "surf",
        "tide",
        "water",
        "swell",
        "beach",
        "current",
    ],
}


def main() -> None:
    missing = [e for e in LABELS["emojis"] if e not in KEYWORDS]
    if missing:
        raise SystemExit(f"no keywords for: {' '.join(missing)}")

    lines: list[str] = []
    for emoji in LABELS["emojis"]:
        for keyword in KEYWORDS[emoji]:
            record = {"emoji": emoji, "feeling": "Neutral", "text": keyword}
            lines.append(json.dumps(record, ensure_ascii=False, separators=(",", ":")))

    out = ROOT / "keywords.jsonl"
    out.write_text("\n".join(lines) + "\n")
    n_emojis = len(LABELS["emojis"])
    print(f"wrote {len(lines)} keywords for {n_emojis} emojis -> {out.name}")


if __name__ == "__main__":
    main()
