"""Generate keywords.jsonl: one keyword per line, same schema as data.jsonl.

Each record is {"emoji": <emoji>, "feeling": <feeling>, "text": <keyword>}.
The keyword list is a hand-curated set of words/short phrases associated with
each emoji in labels.json. Most keywords name a thing and carry no affect, so
they default to "Neutral"; keywords that are *strongly* tied to one feeling
(e.g. "crying", "party", "deadline") override it with a `(keyword, feeling)`
tuple. Run with: uv run gen_keywords.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent
LABELS = json.loads((ROOT / "labels.json").read_text())

# emoji -> list of associated keywords. A bare string defaults to "Neutral";
# a (keyword, feeling) tuple pins a keyword that clearly evokes one feeling.
Keyword = str | tuple[str, str]
KEYWORDS: dict[str, list[Keyword]] = {
    "😀": [
        ("smile", "Happy"),
        ("grin", "Happy"),
        ("grinning", "Happy"),
        ("happy", "Happy"),
        ("cheerful", "Happy"),
        ("beaming", "Happy"),
        ("joy", "Happy"),
        ("smiley", "Happy"),
        ("delighted", "Happy"),
        ("pleased", "Happy"),
        ("glad", "Happy"),
        ("friendly", "Happy"),
        ("big smile", "Happy"),
    ],
    "😂": [
        ("laughing", "Happy"),
        ("lol", "Happy"),
        ("lmao", "Happy"),
        ("rofl", "Happy"),
        ("hilarious", "Happy"),
        ("funny", "Happy"),
        ("laugh", "Happy"),
        ("crying laughing", "Happy"),
        ("humor", "Happy"),
        ("joke", "Happy"),
        ("giggles", "Happy"),
        ("chuckle", "Happy"),
        ("hysterical", "Happy"),
    ],
    "🥹": [
        ("touched", "Happy"),
        "emotional",
        ("grateful", "Happy"),
        ("moved", "Happy"),
        ("teary", "Sad"),
        ("bittersweet", "Sad"),
        ("heartwarming", "Happy"),
        ("proud", "Happy"),
        "overwhelmed",
        "sentimental",
        ("holding back tears", "Sad"),
    ],
    "😍": [
        ("love", "Happy"),
        ("adore", "Happy"),
        ("crush", "Happy"),
        ("infatuated", "Happy"),
        ("heart eyes", "Happy"),
        ("smitten", "Happy"),
        ("admiration", "Happy"),
        ("gorgeous", "Happy"),
        ("beautiful", "Happy"),
        ("obsessed", "Happy"),
        ("love struck", "Happy"),
    ],
    "🤔": [
        "thinking",
        "pondering",
        "hmm",
        "wondering",
        "considering",
        "curious",
        "contemplating",
        "doubt",
        "question",
        "reflecting",
        "puzzled",
    ],
    "🥳": [
        ("celebration", "Excited"),
        ("party", "Excited"),
        ("birthday", "Excited"),
        ("congrats", "Excited"),
        ("festive", "Excited"),
        ("hooray", "Excited"),
        ("celebrate", "Excited"),
        "party horn",
        "confetti",
        ("woohoo", "Excited"),
    ],
    "😎": [
        "cool",
        "sunglasses",
        ("confident", "Happy"),
        ("chill", "Calm"),
        "swag",
        ("awesome", "Excited"),
        "slick",
        "boss",
        ("unbothered", "Calm"),
        "deal with it",
    ],
    "😭": [
        ("crying", "Sad"),
        ("sobbing", "Sad"),
        ("tears", "Sad"),
        ("bawling", "Sad"),
        ("heartbroken", "Sad"),
        ("weeping", "Sad"),
        ("devastated", "Sad"),
        ("wailing", "Sad"),
        ("ugly cry", "Sad"),
        ("so sad", "Sad"),
    ],
    "💀": [
        "skull",
        "dead",
        "death",
        "dying",
        "skeleton",
        "bones",
        "spooky",
        "morbid",
        "danger",
        "poison",
        ("im dead", "Happy"),
    ],
    "🔥": [
        "fire",
        "flame",
        ("lit", "Excited"),
        "hot",
        "burning",
        "blaze",
        "heat",
        "wildfire",
        "campfire",
        ("straight fire", "Excited"),
    ],
    "❤️": [
        ("love", "Happy"),
        "heart",
        ("romance", "Happy"),
        ("affection", "Happy"),
        "valentine",
        ("devotion", "Happy"),
        ("adore", "Happy"),
        ("care", "Happy"),
        ("sweetheart", "Happy"),
        "red heart",
    ],
    "💯": [
        "hundred",
        ("perfect", "Happy"),
        "hundred percent",
        "agreed",
        "full marks",
        "score",
        "absolutely",
        "spot on",
        "keep it real",
    ],
    "✨": [
        "sparkle",
        "shine",
        "glitter",
        "magic",
        "shimmer",
        "glimmer",
        "dazzle",
        "stars",
        "clean",
        "brand new",
        "special",
    ],
    "👍": [
        "thumbs up",
        "approve",
        "okay",
        "yes",
        "agree",
        "like",
        "good",
        "nice",
        "sounds good",
        "will do",
    ],
    "👏": [
        "clap",
        ("applause", "Happy"),
        ("bravo", "Happy"),
        ("well done", "Happy"),
        ("cheer", "Happy"),
        ("ovation", "Happy"),
        ("congrats", "Happy"),
        ("praise", "Happy"),
        ("kudos", "Happy"),
    ],
    "🙌": [
        ("praise", "Happy"),
        ("hooray", "Excited"),
        ("celebration", "Excited"),
        "raised hands",
        ("hallelujah", "Happy"),
        ("yay", "Excited"),
        ("triumph", "Happy"),
        ("relief", "Calm"),
        ("thank goodness", "Calm"),
    ],
    "🙏": [
        ("prayer", "Calm"),
        ("pray", "Calm"),
        "please",
        ("thank you", "Happy"),
        ("gratitude", "Happy"),
        "hope",
        ("blessing", "Calm"),
        ("namaste", "Calm"),
        "plea",
        ("grateful", "Happy"),
    ],
    "💪": [
        "strong",
        "muscle",
        "strength",
        "flex",
        "power",
        "gym",
        "workout",
        "biceps",
        "tough",
        "fitness",
        "gains",
    ],
    "🧠": [
        "brain",
        "mind",
        "smart",
        "intelligence",
        "think",
        "knowledge",
        "brainy",
        "neurons",
        "memory",
        "genius",
    ],
    "👀": [
        "eyes",
        "looking",
        "watching",
        "see",
        "peek",
        "suspicious",
        "spying",
        "attention",
        "staring",
        "look",
    ],
    "🐶": [
        "dog",
        "puppy",
        "doggo",
        "pup",
        "canine",
        "pooch",
        "hound",
        "woof",
        "pet",
        "good boy",
    ],
    "🐱": [
        "cat",
        "kitten",
        "kitty",
        "feline",
        "meow",
        "tabby",
        "whiskers",
        "pet",
        "house cat",
    ],
    "🦁": [
        "lion",
        "king",
        "mane",
        "jungle",
        "safari",
        "leo",
        "roar",
        "big cat",
        "pride",
        "wild",
    ],
    "🦉": [
        "owl",
        "night owl",
        "wise",
        "hoot",
        "bird",
        "nocturnal",
        "wisdom",
        "feathers",
    ],
    "🐙": [
        "octopus",
        "tentacles",
        "sea creature",
        "cephalopod",
        "ocean",
        "eight arms",
        "kraken",
        "marine",
    ],
    "🌲": [
        "tree",
        "pine",
        "forest",
        "evergreen",
        "woods",
        "nature",
        "conifer",
        "spruce",
        "wilderness",
        "hiking",
    ],
    "🌺": [
        "flower",
        "hibiscus",
        "bloom",
        "tropical",
        "blossom",
        "floral",
        "petal",
        "hawaii",
        "garden",
    ],
    "🌈": [
        "rainbow",
        "colors",
        "pride",
        "spectrum",
        "arc",
        "hope",
        "colorful",
        "prism",
        "after the rain",
    ],
    "☀️": [
        "sun",
        "sunny",
        "sunshine",
        "daylight",
        "bright",
        "summer",
        "solar",
        "warmth",
        "clear sky",
    ],
    "⭐": [
        "star",
        "favorite",
        "rating",
        "shine",
        "gold star",
        "celebrity",
        "twinkle",
        "wish",
        "five stars",
    ],
    "🍕": [
        "pizza",
        "slice",
        "pepperoni",
        "cheese",
        "italian",
        "pie",
        "pizzeria",
        "takeout",
        "dough",
    ],
    "🌮": [
        "taco",
        "mexican",
        "tex mex",
        "tortilla",
        "taco tuesday",
        "salsa",
        "food truck",
        "filling",
    ],
    "🍣": [
        "sushi",
        "sashimi",
        "nigiri",
        "japanese",
        "raw fish",
        "rice",
        "roll",
        "wasabi",
        "seafood",
    ],
    "☕": [
        "coffee",
        "tea",
        "espresso",
        "latte",
        "cafe",
        "caffeine",
        "mug",
        "brew",
        "morning",
        "cappuccino",
    ],
    "🍺": [
        "beer",
        "brew",
        "pint",
        "ale",
        "lager",
        "pub",
        "cheers",
        "draft",
        "brewery",
        "drinks",
    ],
    "⚽": [
        "soccer",
        "football",
        "ball",
        "goal",
        "pitch",
        "world cup",
        "kick",
        "match",
        "fifa",
        "sport",
    ],
    "🎉": [
        ("party", "Excited"),
        ("celebration", "Excited"),
        "confetti",
        ("congrats", "Excited"),
        "popper",
        ("hooray", "Excited"),
        ("festive", "Excited"),
        "new year",
        ("celebrate", "Excited"),
    ],
    "🚀": [
        "rocket",
        "space",
        "launch",
        "spaceship",
        "blast off",
        "nasa",
        "astronaut",
        "moon",
        "orbit",
        "startup",
    ],
    "✈️": [
        "airplane",
        "plane",
        "flight",
        "travel",
        "jet",
        "airport",
        "flying",
        "vacation",
        "aviation",
        "trip",
    ],
    "🎸": [
        "guitar",
        "music",
        "rock",
        "band",
        "strings",
        "electric guitar",
        "riff",
        "strum",
        "musician",
    ],
    "💡": [
        "idea",
        "light bulb",
        "insight",
        "inspiration",
        "bright idea",
        "invention",
        ("eureka", "Excited"),
        "lamp",
        "innovation",
    ],
    "💎": [
        "diamond",
        "gem",
        "jewel",
        "gemstone",
        "precious",
        "crystal",
        "treasure",
        "luxury",
        "bling",
    ],
    "📱": [
        "phone",
        "smartphone",
        "mobile",
        "cellphone",
        "texting",
        "screen",
        "apps",
        "call",
        "device",
    ],
    "🎁": [
        "gift",
        "present",
        "wrapped",
        "birthday",
        "surprise",
        "package",
        "bow",
        "giveaway",
        "holiday",
    ],
    "🔒": [
        "lock",
        "locked",
        "secure",
        "security",
        "privacy",
        "password",
        "padlock",
        "safe",
        "encrypted",
        "protected",
    ],
    "🌍": [
        "earth",
        "world",
        "globe",
        "planet",
        "global",
        "international",
        "environment",
        "map",
        "continents",
    ],
    "🏆": [
        "trophy",
        "award",
        ("winner", "Happy"),
        ("champion", "Happy"),
        ("first place", "Happy"),
        "prize",
        ("victory", "Excited"),
        "championship",
        "cup",
    ],
    "🎨": [
        "art",
        "painting",
        "palette",
        "paint",
        "artist",
        "creative",
        "colors",
        "canvas",
        "drawing",
        "design",
    ],
    "🔮": [
        "crystal ball",
        "fortune",
        "future",
        "prediction",
        "mystic",
        "psychic",
        "magic",
        "divination",
        "tarot",
    ],
    "📍": [
        "pin",
        "location",
        "map",
        "marker",
        "place",
        "gps",
        "destination",
        "address",
        "you are here",
    ],
    "💼": [
        "briefcase",
        "work",
        "business",
        "office",
        "job",
        "career",
        "corporate",
        "professional",
        "meeting",
    ],
    "🩺": [
        "stethoscope",
        "doctor",
        "medical",
        "health",
        "checkup",
        "nurse",
        "clinic",
        "physician",
        "healthcare",
    ],
    "💻": [
        "laptop",
        "computer",
        "coding",
        "programming",
        "tech",
        "notebook",
        "screen",
        "remote work",
        "software",
    ],
    "⏰": [
        "alarm",
        "clock",
        "time",
        "wake up",
        "morning",
        ("deadline", "Anxious"),
        "reminder",
        "alarm clock",
        "snooze",
    ],
    "🚗": [
        "car",
        "automobile",
        "drive",
        "vehicle",
        "road trip",
        "traffic",
        "sedan",
        "commute",
        "driving",
    ],
    "🌾": [
        "wheat",
        "grain",
        "harvest",
        "farm",
        "field",
        "agriculture",
        "crop",
        "rural",
        "countryside",
    ],
    "⛈️": [
        "storm",
        "thunderstorm",
        "lightning",
        "rain",
        "thunder",
        "weather",
        "downpour",
        "tempest",
    ],
    "🧩": [
        "puzzle",
        "jigsaw",
        "piece",
        "solution",
        "problem solving",
        "fit",
        "missing piece",
        "brain teaser",
    ],
    "👑": [
        "crown",
        "king",
        "queen",
        "royalty",
        "royal",
        "monarch",
        "ruler",
        "throne",
        "tiara",
        "majesty",
    ],
    "🕊️": [
        "dove",
        ("peace", "Calm"),
        "bird",
        "pigeon",
        ("freedom", "Calm"),
        "hope",
        ("olive branch", "Calm"),
        ("harmony", "Calm"),
        ("tranquility", "Calm"),
    ],
    "🤩": [
        ("star struck", "Excited"),
        ("amazed", "Excited"),
        ("excited", "Excited"),
        ("wow", "Excited"),
        ("starry eyes", "Excited"),
        ("awesome", "Excited"),
        ("thrilled", "Excited"),
        ("fascinated", "Excited"),
        ("dazzled", "Excited"),
    ],
    "😴": [
        ("sleep", "Calm"),
        ("sleeping", "Calm"),
        "tired",
        ("nap", "Calm"),
        ("zzz", "Calm"),
        ("snooze", "Calm"),
        ("drowsy", "Calm"),
        ("bedtime", "Calm"),
        ("asleep", "Calm"),
        "exhausted",
    ],
    "🤡": [
        "clown",
        "circus",
        "joker",
        "jester",
        "silly",
        "foolish",
        "prank",
        "makeup",
        "honk",
    ],
    "🤖": [
        "robot",
        "bot",
        "ai",
        "android",
        "machine",
        "automation",
        "cyborg",
        "mechanical",
        "artificial intelligence",
    ],
    "👻": [
        "ghost",
        "spooky",
        "halloween",
        "boo",
        "haunted",
        "spirit",
        "phantom",
        "apparition",
        ("scary", "Anxious"),
    ],
    "🤝": [
        "handshake",
        "deal",
        "agreement",
        "partnership",
        "meeting",
        "greeting",
        "cooperation",
        "contract",
        "shake hands",
    ],
    "🫡": [
        "salute",
        "respect",
        "yes sir",
        "acknowledge",
        "military",
        "honor",
        "at attention",
        "will do",
    ],
    "🫶": [
        "heart hands",
        ("love", "Happy"),
        ("appreciation", "Happy"),
        ("thank you", "Happy"),
        ("care", "Happy"),
        ("gratitude", "Happy"),
        ("adore", "Happy"),
        ("support", "Happy"),
    ],
    "💔": [
        ("broken heart", "Sad"),
        ("heartbreak", "Sad"),
        ("breakup", "Sad"),
        ("hurt", "Sad"),
        ("grief", "Sad"),
        ("lost love", "Sad"),
        ("heartbroken", "Sad"),
        ("pain", "Sad"),
    ],
    "🌶️": [
        "chili",
        "pepper",
        "spicy",
        "hot",
        "jalapeno",
        "chilli",
        "heat",
        "cayenne",
        "hot sauce",
    ],
    "🍦": [
        "ice cream",
        "soft serve",
        "cone",
        "dessert",
        "sweet",
        "vanilla",
        "summer treat",
        "frozen",
    ],
    "🍩": [
        "donut",
        "doughnut",
        "pastry",
        "sweet",
        "glazed",
        "sprinkles",
        "bakery",
        "treat",
    ],
    "🎬": [
        "movie",
        "film",
        "cinema",
        "action",
        "clapperboard",
        "director",
        "hollywood",
        "filming",
        "scene",
    ],
    "🎧": [
        "headphones",
        "music",
        "audio",
        "listening",
        "podcast",
        "headset",
        "sound",
        "earphones",
        "dj",
    ],
    "🎮": [
        "gaming",
        "video game",
        "controller",
        "gamepad",
        "console",
        "play",
        "gamer",
        "esports",
        "joystick",
    ],
    "📚": [
        "books",
        "reading",
        "library",
        "study",
        "education",
        "literature",
        "textbooks",
        "learning",
        "novels",
    ],
    "🕯️": [
        "candle",
        "flame",
        "wax",
        ("candlelight", "Calm"),
        ("vigil", "Sad"),
        ("meditation", "Calm"),
        ("cozy", "Calm"),
        "light",
        "wick",
    ],
    "⚡": [
        "lightning",
        "electricity",
        "power",
        "energy",
        "bolt",
        "voltage",
        "spark",
        "charge",
        "fast",
    ],
    "🍀": [
        "clover",
        "luck",
        "lucky",
        "four leaf clover",
        "shamrock",
        "fortune",
        "st patricks",
        "irish",
        "good luck",
    ],
    "🌊": [
        "wave",
        "ocean",
        "sea",
        "surf",
        "tide",
        "water",
        "swell",
        "beach",
        "current",
    ],
}


def main() -> None:
    missing = [e for e in LABELS["emojis"] if e not in KEYWORDS]
    if missing:
        raise SystemExit(f"no keywords for: {' '.join(missing)}")

    valid_feelings = set(LABELS["feelings"])
    lines: list[str] = []
    for emoji in LABELS["emojis"]:
        for entry in KEYWORDS[emoji]:
            keyword, feeling = entry if isinstance(entry, tuple) else (entry, "Neutral")
            if feeling not in valid_feelings:
                raise SystemExit(f"unknown feeling {feeling!r} for keyword {keyword!r}")
            record = {"emoji": emoji, "feeling": feeling, "text": keyword}
            lines.append(json.dumps(record, ensure_ascii=False, separators=(",", ":")))

    out = ROOT / "keywords.jsonl"
    out.write_text("\n".join(lines) + "\n")
    n_emojis = len(LABELS["emojis"])
    print(f"wrote {len(lines)} keywords for {n_emojis} emojis -> {out.name}")


if __name__ == "__main__":
    main()
